services:
  # Serviço da API
  tasq.projetos.api:
    image: ${DOCKER_REGISTRY-}tasq-projetos-api
    build:
      context: .
      dockerfile: src/TasQ.Projetos.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ConnectionStrings__DefaultConnection=Host=tasq.postgres;Port=5432;Database=db_tasq;Username=root;Password=pgsqlpwd
    ports:
      - "5000:5000"
    depends_on:
      tasq.postgres:
        condition: service_healthy
    networks:
      - app-network

  # Serviço do PostgreSQL
  tasq.postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pgsqlpwd
      POSTGRES_DB: db_tasq
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db_tasq"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge